### ISSUE TITLE
您好，目前似乎无法使用，不报错但不抓取图片？对py不太了解不能提供更多信息

### ISSUE THREAD

**Issue by Chankalam** [gamblenull1996/zhihu_favorites_spider#1]

**Comment by gaoquanao** [comment]
刚才我在我的电脑上测试了collect_pic.py和zhihu_pool.py
都是没有问题的，开始下载图片后会不停打印辅助信息的(包括正在下载的图片链接，下载成功与否等)。
由于没有更多信息提供给我，我也不知道到底是什么问题。
首先确保你的python版本为2.7
安装好了requests， BeautifulSoup
py脚本以管理员权限运行
最好给我运行的截图。

**Comment by Chankalam** [comment]
抱歉，刚才仔细翻了代码，发现是只抓取收藏中的单条回答，目前已可正常运行，感谢。
